package org.cvte.research.faceapi.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.swee1.pengyouquan.domain.Contact;
import com.example.swee1.pengyouquan.domain.Config;

import org.cvte.research.faceapi.greendao.ContactDao;
import org.cvte.research.faceapi.greendao.ConfigDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig contactDaoConfig;
    private final DaoConfig configDaoConfig;

    private final ContactDao contactDao;
    private final ConfigDao configDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        contactDaoConfig = daoConfigMap.get(ContactDao.class).clone();
        contactDaoConfig.initIdentityScope(type);

        configDaoConfig = daoConfigMap.get(ConfigDao.class).clone();
        configDaoConfig.initIdentityScope(type);

        contactDao = new ContactDao(contactDaoConfig, this);
        configDao = new ConfigDao(configDaoConfig, this);

        registerDao(Contact.class, contactDao);
        registerDao(Config.class, configDao);
    }
    
    public void clear() {
        contactDaoConfig.clearIdentityScope();
        configDaoConfig.clearIdentityScope();
    }

    public ContactDao getContactDao() {
        return contactDao;
    }

    public ConfigDao getConfigDao() {
        return configDao;
    }

}
