package org.cvte.research.faceapi.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.swee1.pengyouquan.domain.FriendBean;
import com.example.swee1.pengyouquan.domain.ConfigBean;

import org.cvte.research.faceapi.greendao.FriendBeanDao;
import org.cvte.research.faceapi.greendao.ConfigBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig friendBeanDaoConfig;
    private final DaoConfig configBeanDaoConfig;

    private final FriendBeanDao friendBeanDao;
    private final ConfigBeanDao configBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        friendBeanDaoConfig = daoConfigMap.get(FriendBeanDao.class).clone();
        friendBeanDaoConfig.initIdentityScope(type);

        configBeanDaoConfig = daoConfigMap.get(ConfigBeanDao.class).clone();
        configBeanDaoConfig.initIdentityScope(type);

        friendBeanDao = new FriendBeanDao(friendBeanDaoConfig, this);
        configBeanDao = new ConfigBeanDao(configBeanDaoConfig, this);

        registerDao(FriendBean.class, friendBeanDao);
        registerDao(ConfigBean.class, configBeanDao);
    }
    
    public void clear() {
        friendBeanDaoConfig.clearIdentityScope();
        configBeanDaoConfig.clearIdentityScope();
    }

    public FriendBeanDao getFriendBeanDao() {
        return friendBeanDao;
    }

    public ConfigBeanDao getConfigBeanDao() {
        return configBeanDao;
    }

}
